name: Build

on: [workflow_dispatch, push]

jobs:
  build_on_win:
    name: Build on Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - uses: microsoft/setup-msbuild@v1.0.2
    # OBS Studio
    - run: curl -L -o dependencies2019.zip http://obsproject.com/downloads/dependencies2019.zip
    - run: 7z x -odependencies2019 dependencies2019.zip
    - run: git clone --recursive https://github.com/stream-labs/obs-studio
    - run: tree
    - run: mkdir build
      working-directory: obs-studio
    - run: cmake -G"Visual Studio 16 2019" -A x64 -S . -DENABLE_UI=false -DDepsPath="..\dependencies2019\win64" -DENABLE_SCRIPTING=false
      working-directory: obs-studio
    - run: cmake --config Release
      working-directory: obs-studio/build
    - run: cpack -G ZIP
      working-directory: obs-studio/build
    - run: tree
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    # obs-studio-node
    - run: git clone https://github.com/stream-labs/obs-studio-node
    - run: yarn install
      working-directory: obs-studio-node
    - run: git submodule update --init --recursive
      working-directory: obs-studio-node
    - run: mkdir build
      working-directory: obs-studio-node
    - run: cmake .. -G"Visual Studio 15 2017" -A x64 -DOSN_LIBOBS_URL="../../obs-studio/build/obs-studio-x64-22.0.3-sl-7-13-g208cb2f5.zip"
      working-directory: obs-studio-node/build
    - run: cmake --build . --config Release
      working-directory: obs-studio-node/build
    - run: cpack -G ZIP
      working-directory: obs-studio-node/build
    - run: tree
    - uses: actions/upload-artifact@v2
      with:
        name: obs-studio-node-0.3.21-win64.zip
        path: obs-studio-node/build/*.zip